In [1]:
# Step1. NumPyをインポートする
import numpy as np

# Step2. AとBの行列を格納する多次元配列の定義
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Step3. 行列の積を計算する
C = np.dot(A, B)

# Step4. 計算結果を表示する
print("行列の積 A × B の結果：")
print(C)

# Step5. 行列の要素の最大値を求めて表示する
max_value = np.max(C)
print("行列の最大値：", max_value)

行列の積 A × B の結果：
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の最大値： 47
